version: '3.8'

services:
  backend-blue:
    build: ../PhotoGuestsAI-Backend
    container_name: fastapi-backend-blue
    restart: always
    environment:
      - ENV=production
    ports:
      - "8000:8000"
    networks:
      - app-network

  backend-green:
    build: ../PhotoGuestsAI-Backend
    container_name: fastapi-backend-green
    restart: always
    environment:
      - ENV=production
    ports:
      - "8001:8000"
    networks:
      - app-network

  frontend-blue:
    build: .
    container_name: react-frontend-blue
    restart: always
    ports:
      - "3000:80"
    networks:
      - app-network

  frontend-green:
    build: .
    container_name: react-frontend-green
    restart: always
    ports:
      - "3001:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
