version: "3.8"

services:
  frontend:
    build: .
    container_name: react-frontend
    ports:
      - "80:80"
    restart: always
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
