version: '3.8'

services:
  frontend-blue:
    build: .
    container_name: react-frontend-blue
    restart: always
    ports:
      - "3000:80"
    networks:
      - frontend-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  frontend-green:
    build: .
    container_name: react-frontend-green
    restart: always
    ports:
      - "3001:80"
    networks:
      - frontend-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  frontend-network:
    driver: bridge
